services:
  app:
    image: node:14.19.0-alpine
    command: sh -c "npm install && npm start"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      NODE_ENV: development

