services:
  app:
    build:
      context: .
      # dockerfile: Dockerfile.dev
      target: development
    ports:
      - 3001:3000
    volumes:
      - ./:/app
    environment:
      NODE_ENV: development

